include:
    - ./testing-Billing/attendify-billing/docker-compose.testing.yml
    - ./testing-Frontend/attendify-frontend/docker-compose.yaml
    - ./testing-Frontend/attendify-frontend/docker-compose.test.yaml
    - ./testing-Planning/attendify-planning/planning/docker-compose.yml
    - ./testing-Planning/attendify-planning/planning/docker-compose.test.yml
    - ./testing-CRM/Attendify_CRM/docker-compose-testing.yml
networks:
  attendify_net_testing:
    driver: bridge
services:
  rabbitmq:
      image: rabbitmq:4-management
      container_name: some-rabbit-testing
      restart: always
      environment:
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
        RABBITMQ_DEFAULT_USER: attendify
        RABBITMQ_DEFAULT_VHOST: attendify
      ports:
        - "30096:15672"
        - "30097:5672"
      volumes:
        - ./rabbitmq/volumes/rabbitmq/data:/var/lib/rabbitmq
      networks:
        - attendify_net_testing