networks:
  attendify_net:
    external: true
include:
    - ./attendify-billing/docker-compose.prod.yml
    - ./attendify-frontend/docker-compose.yml
    - ./attendify-frontend/docker-compose.prod.yml
    - ./attendify-planning/planning/docker-compose.prod.yml
    - ./attendify-planning/planning/docker-compose.yml
    - ./Attendify_CRM/docker-compose.yml
services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: some-rabbit
    restart: always
    environment:
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_USER: attendify
      RABBITMQ_DEFAULT_VHOST: attendify
    ports:
      - "30000:15672"
      - "30001:5672"
    volumes:
      - ./rabbitmq/volumes/rabbitmq/data:/var/lib/rabbitmq
    networks:
      - attendify_net